Search.appendIndex(
    [
                {
            "fqsen": "\\myrpc\\ApiServer",
            "name": "ApiServer",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#method_run"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024handlerFactory",
            "name": "handlerFactory",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_handlerFactory"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_requestFactory"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_responseFactory"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024identityFactory",
            "name": "identityFactory",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_identityFactory"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024schemaFactory",
            "name": "schemaFactory",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_schemaFactory"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024handlerContextFactory",
            "name": "handlerContextFactory",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_handlerContextFactory"
        },                {
            "fqsen": "\\myrpc\\ApiServer\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/myrpc-ApiServer.html#property_logger"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory",
            "name": "DatatypeFactory",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003AhasUserspaceType\u0028\u0029",
            "name": "hasUserspaceType",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#method_hasUserspaceType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003AgetUserspaceType\u0028\u0029",
            "name": "getUserspaceType",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#method_getUserspaceType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003AgetInternalErrorResponseType\u0028\u0029",
            "name": "getInternalErrorResponseType",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#method_getInternalErrorResponseType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003AgetInternalSuccessResponseType\u0028\u0029",
            "name": "getInternalSuccessResponseType",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#method_getInternalSuccessResponseType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactory\u003A\u003A\u0024typesSource",
            "name": "typesSource",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactory.html#property_typesSource"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactoryInterface",
            "name": "DatatypeFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactoryInterface\u003A\u003AgetInternalErrorResponseType\u0028\u0029",
            "name": "getInternalErrorResponseType",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactoryInterface.html#method_getInternalErrorResponseType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeFactoryInterface\u003A\u003AgetInternalSuccessResponseType\u0028\u0029",
            "name": "getInternalSuccessResponseType",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeFactoryInterface.html#method_getInternalSuccessResponseType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeInterface",
            "name": "DatatypeInterface",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeInterface.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\DatatypeInterface\u003A\u003AgetPayload\u0028\u0029",
            "name": "getPayload",
            "summary": "",
            "url": "classes/myrpc-Datatype-DatatypeInterface.html#method_getPayload"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\AbstractDatatype",
            "name": "AbstractDatatype",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-AbstractDatatype.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\AbstractDatatype\u003A\u003AgetPayload\u0028\u0029",
            "name": "getPayload",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-AbstractDatatype.html#method_getPayload"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\AbstractDatatype\u003A\u003AvalidatableObject\u0028\u0029",
            "name": "validatableObject",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-AbstractDatatype.html#method_validatableObject"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Error",
            "name": "Error",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Error.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Error\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Error.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Error\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Error.html#property_error"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Error\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Error.html#property_code"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Success",
            "name": "Success",
            "summary": "This\u0020is\u0020generic\u0020success\u0020response",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Success.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Success\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020response\u0020will\u0020NOT\u0020have\u0020any\u0020type\u002Dspecific\u0020schema\u0020for\u0020it\u0027s\u0020payload\nUsage\u0020only\u0020with\u0020built\u002Din\u0020types\u0020is\u0020recommended\nUsage\u0020with\u0020array\u0020or\u0020object\u0020is\u0020NOT\u0020recommended",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Success.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response\\Success\u003A\u003A\u0024success",
            "name": "success",
            "summary": "",
            "url": "classes/myrpc-Datatype-Internal-v1-Response-Success.html#property_success"
        },                {
            "fqsen": "\\myrpc\\Datatype\\UserspaceDatatypeFactoryInterface",
            "name": "UserspaceDatatypeFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Datatype-UserspaceDatatypeFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\UserspaceDatatypeFactoryInterface\u003A\u003AhasUserspaceType\u0028\u0029",
            "name": "hasUserspaceType",
            "summary": "",
            "url": "classes/myrpc-Datatype-UserspaceDatatypeFactoryInterface.html#method_hasUserspaceType"
        },                {
            "fqsen": "\\myrpc\\Datatype\\UserspaceDatatypeFactoryInterface\u003A\u003AgetUserspaceType\u0028\u0029",
            "name": "getUserspaceType",
            "summary": "",
            "url": "classes/myrpc-Datatype-UserspaceDatatypeFactoryInterface.html#method_getUserspaceType"
        },                {
            "fqsen": "\\myrpc\\Exception\\DatatypeException",
            "name": "DatatypeException",
            "summary": "",
            "url": "classes/myrpc-Exception-DatatypeException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\HandlerActionArgumentsException",
            "name": "HandlerActionArgumentsException",
            "summary": "",
            "url": "classes/myrpc-Exception-HandlerActionArgumentsException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\HandlerActionException",
            "name": "HandlerActionException",
            "summary": "",
            "url": "classes/myrpc-Exception-HandlerActionException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\HandlerActionInputException",
            "name": "HandlerActionInputException",
            "summary": "",
            "url": "classes/myrpc-Exception-HandlerActionInputException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\HandlerActionSerializerException",
            "name": "HandlerActionSerializerException",
            "summary": "",
            "url": "classes/myrpc-Exception-HandlerActionSerializerException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\HandlerActionTypeException",
            "name": "HandlerActionTypeException",
            "summary": "",
            "url": "classes/myrpc-Exception-HandlerActionTypeException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\HandlerActionValidationException",
            "name": "HandlerActionValidationException",
            "summary": "",
            "url": "classes/myrpc-Exception-HandlerActionValidationException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\SerializerException",
            "name": "SerializerException",
            "summary": "",
            "url": "classes/myrpc-Exception-SerializerException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\SerializerObjectAssertException",
            "name": "SerializerObjectAssertException",
            "summary": "",
            "url": "classes/myrpc-Exception-SerializerObjectAssertException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\ServiceAuthenticationException",
            "name": "ServiceAuthenticationException",
            "summary": "",
            "url": "classes/myrpc-Exception-ServiceAuthenticationException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\ServiceException",
            "name": "ServiceException",
            "summary": "",
            "url": "classes/myrpc-Exception-ServiceException.html"
        },                {
            "fqsen": "\\myrpc\\Exception\\ServiceException\u003A\u003AgetLogMessage\u0028\u0029",
            "name": "getLogMessage",
            "summary": "",
            "url": "classes/myrpc-Exception-ServiceException.html#method_getLogMessage"
        },                {
            "fqsen": "\\myrpc\\Exception\\ServiceException\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/myrpc-Exception-ServiceException.html#property_code"
        },                {
            "fqsen": "\\myrpc\\Exception\\ValidatorException",
            "name": "ValidatorException",
            "summary": "",
            "url": "classes/myrpc-Exception-ValidatorException.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context",
            "name": "Context",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AnewErrorResponse\u0028\u0029",
            "name": "newErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_newErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AnewSuccessResponse\u0028\u0029",
            "name": "newSuccessResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_newSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AnewDatatypeResponse\u0028\u0029",
            "name": "newDatatypeResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_newDatatypeResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AsetIdentity\u0028\u0029",
            "name": "setIdentity",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_setIdentity"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AgetIdentity\u0028\u0029",
            "name": "getIdentity",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_getIdentity"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AsetAction\u0028\u0029",
            "name": "setAction",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_setAction"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AsetArguments\u0028\u0029",
            "name": "setArguments",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_setArguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AgetAction\u0028\u0029",
            "name": "getAction",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_getAction"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003AgetArguments\u0028\u0029",
            "name": "getArguments",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#method_getArguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003A\u0024identity",
            "name": "identity",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#property_identity"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#property_action"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003A\u0024arguments",
            "name": "arguments",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#property_arguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003A\u0024handlerResponseFactory",
            "name": "handlerResponseFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#property_handlerResponseFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\Context\u003A\u003A\u0024userspaceDatatypeFactory",
            "name": "userspaceDatatypeFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-Context.html#property_userspaceDatatypeFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactory",
            "name": "ContextFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactory.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactory.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactory.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactory\u003A\u003A\u0024responseFactory",
            "name": "responseFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactory.html#property_responseFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactory\u003A\u003A\u0024datatypeFactory",
            "name": "datatypeFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactory.html#property_datatypeFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactoryInterface",
            "name": "ContextFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextFactoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextFactoryInterface.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextInterface",
            "name": "ContextInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface",
            "name": "ContextReaderInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface\u003A\u003AgetIdentity\u0028\u0029",
            "name": "getIdentity",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html#method_getIdentity"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface\u003A\u003AgetAction\u0028\u0029",
            "name": "getAction",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html#method_getAction"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface\u003A\u003AgetArguments\u0028\u0029",
            "name": "getArguments",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html#method_getArguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface\u003A\u003AnewErrorResponse\u0028\u0029",
            "name": "newErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html#method_newErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface\u003A\u003AnewSuccessResponse\u0028\u0029",
            "name": "newSuccessResponse",
            "summary": "Do\u0020not\u0020allow\u0020returning\u0020stdClass,\u0020all\u0020objects\u0020need\u0020to\u0020be\u0020typed",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html#method_newSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextReaderInterface\u003A\u003AnewDatatypeResponse\u0028\u0029",
            "name": "newDatatypeResponse",
            "summary": "Use\u0020user\u002Ddefined\u0020types\u0020as\u0020response",
            "url": "classes/myrpc-Handler-Context-ContextReaderInterface.html#method_newDatatypeResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextWriterInterface",
            "name": "ContextWriterInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextWriterInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextWriterInterface\u003A\u003AsetIdentity\u0028\u0029",
            "name": "setIdentity",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextWriterInterface.html#method_setIdentity"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextWriterInterface\u003A\u003AsetAction\u0028\u0029",
            "name": "setAction",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextWriterInterface.html#method_setAction"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context\\ContextWriterInterface\u003A\u003AsetArguments\u0028\u0029",
            "name": "setArguments",
            "summary": "",
            "url": "classes/myrpc-Handler-Context-ContextWriterInterface.html#method_setArguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory",
            "name": "HandlerFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003AhasSchema\u0028\u0029",
            "name": "hasSchema",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#method_hasSchema"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003AhasContext\u0028\u0029",
            "name": "hasContext",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#method_hasContext"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003AwithContext\u0028\u0029",
            "name": "withContext",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#method_withContext"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#method_withSchema"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003A\u0024handlersSource",
            "name": "handlersSource",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#property_handlersSource"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactory\u003A\u003A\u0024datatypeFactory",
            "name": "datatypeFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactory.html#property_datatypeFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactoryInterface",
            "name": "HandlerFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactoryInterface.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactoryInterface\u003A\u003AhasContext\u0028\u0029",
            "name": "hasContext",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactoryInterface.html#method_hasContext"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactoryInterface\u003A\u003AwithContext\u0028\u0029",
            "name": "withContext",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactoryInterface.html#method_withContext"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactoryInterface\u003A\u003AhasSchema\u0028\u0029",
            "name": "hasSchema",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactoryInterface.html#method_hasSchema"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerFactoryInterface\u003A\u003AwithSchema\u0028\u0029",
            "name": "withSchema",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerFactoryInterface.html#method_withSchema"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerInterface",
            "name": "HandlerInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerInterface\u003A\u003Aaction\u0028\u0029",
            "name": "action",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerInterface.html#method_action"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse",
            "name": "HandlerResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html#method_getResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse\u003A\u003A\u0024isError",
            "name": "isError",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html#property_isError"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse\u003A\u003AgetErrorCode\u0028\u0029",
            "name": "getErrorCode",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html#method_getErrorCode"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html#property_response"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponse\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponse.html#property_code"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseFactory",
            "name": "HandlerResponseFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseFactory.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseFactory\u003A\u003AcreateErrorResponse\u0028\u0029",
            "name": "createErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseFactory.html#method_createErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseFactory\u003A\u003AcreateSuccessResponse\u0028\u0029",
            "name": "createSuccessResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseFactory.html#method_createSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseFactoryInterface",
            "name": "HandlerResponseFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseFactoryInterface\u003A\u003AcreateErrorResponse\u0028\u0029",
            "name": "createErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseFactoryInterface.html#method_createErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseFactoryInterface\u003A\u003AcreateSuccessResponse\u0028\u0029",
            "name": "createSuccessResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseFactoryInterface.html#method_createSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseInterface",
            "name": "HandlerResponseInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseInterface\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseInterface.html#method_getResponse"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseInterface\u003A\u003AisError\u0028\u0029",
            "name": "isError",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseInterface.html#method_isError"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerResponseInterface\u003A\u003AgetErrorCode\u0028\u0029",
            "name": "getErrorCode",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerResponseInterface.html#method_getErrorCode"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerSchemaInterface",
            "name": "HandlerSchemaInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerSchemaInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerSchemaInterface\u003A\u003AsetSchemaFactory\u0028\u0029",
            "name": "setSchemaFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerSchemaInterface.html#method_setSchemaFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerSchemaInterface\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerSchemaInterface.html#method_getSchema"
        },                {
            "fqsen": "\\myrpc\\Handler\\HandlerWithSchemaInterface",
            "name": "HandlerWithSchemaInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-HandlerWithSchemaInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler",
            "name": "SmartHandler",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003Aaction\u0028\u0029",
            "name": "action",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method_action"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003AsetContext\u0028\u0029",
            "name": "setContext",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method_setContext"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003AsetSchemaFactory\u0028\u0029",
            "name": "setSchemaFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method_setSchemaFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003AgetSchema\u0028\u0029",
            "name": "getSchema",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method_getSchema"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003AprepareArguments\u0028\u0029",
            "name": "prepareArguments",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method_prepareArguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003AresolveArguments\u0028\u0029",
            "name": "resolveArguments",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#method_resolveArguments"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A\u0024context",
            "name": "context",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#property_context"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A\u0024reflectionClass",
            "name": "reflectionClass",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#property_reflectionClass"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A\u0024schemaFactory",
            "name": "schemaFactory",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#property_schemaFactory"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A\u0024serializer",
            "name": "serializer",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#property_serializer"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#property_validator"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandler\u003A\u003A\u0024worker",
            "name": "worker",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandler.html#property_worker"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandlerInterface",
            "name": "SmartHandlerInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandlerInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\SmartHandlerInterface\u003A\u003AsetContext\u0028\u0029",
            "name": "setContext",
            "summary": "",
            "url": "classes/myrpc-Handler-SmartHandlerInterface.html#method_setContext"
        },                {
            "fqsen": "\\myrpc\\Handler\\Worker\\WorkerInterface",
            "name": "WorkerInterface",
            "summary": "",
            "url": "classes/myrpc-Handler-Worker-WorkerInterface.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Worker\\WorkerInterface\u003A\u003AsetupWorker\u0028\u0029",
            "name": "setupWorker",
            "summary": "",
            "url": "classes/myrpc-Handler-Worker-WorkerInterface.html#method_setupWorker"
        },                {
            "fqsen": "\\myrpc\\Handler\\Worker\\WorkerTrait",
            "name": "WorkerTrait",
            "summary": "",
            "url": "classes/myrpc-Handler-Worker-WorkerTrait.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Worker\\WorkerTrait\u003A\u003AsetupWorker\u0028\u0029",
            "name": "setupWorker",
            "summary": "",
            "url": "classes/myrpc-Handler-Worker-WorkerTrait.html#method_setupWorker"
        },                {
            "fqsen": "\\myrpc\\Handler\\Worker\\WorkerTrait\u003A\u003A\u0024context",
            "name": "context",
            "summary": "",
            "url": "classes/myrpc-Handler-Worker-WorkerTrait.html#property_context"
        },                {
            "fqsen": "\\myrpc\\Identity\\IdentityFactoryInterface",
            "name": "IdentityFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Identity-IdentityFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Identity\\IdentityFactoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Identity-IdentityFactoryInterface.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Identity\\IdentityInterface",
            "name": "IdentityInterface",
            "summary": "",
            "url": "classes/myrpc-Identity-IdentityInterface.html"
        },                {
            "fqsen": "\\myrpc\\Identity\\IdentityInterface\u003A\u003AgetIdentityToken\u0028\u0029",
            "name": "getIdentityToken",
            "summary": "",
            "url": "classes/myrpc-Identity-IdentityInterface.html#method_getIdentityToken"
        },                {
            "fqsen": "\\myrpc\\Identity\\TokenIdentity",
            "name": "TokenIdentity",
            "summary": "",
            "url": "classes/myrpc-Identity-TokenIdentity.html"
        },                {
            "fqsen": "\\myrpc\\Identity\\TokenIdentity\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Identity-TokenIdentity.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Identity\\TokenIdentity\u003A\u003AgetIdentityToken\u0028\u0029",
            "name": "getIdentityToken",
            "summary": "",
            "url": "classes/myrpc-Identity-TokenIdentity.html#method_getIdentityToken"
        },                {
            "fqsen": "\\myrpc\\Identity\\TokenIdentity\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/myrpc-Identity-TokenIdentity.html#property_token"
        },                {
            "fqsen": "\\myrpc\\Identity\\TokenIdentityFactory",
            "name": "TokenIdentityFactory",
            "summary": "",
            "url": "classes/myrpc-Identity-TokenIdentityFactory.html"
        },                {
            "fqsen": "\\myrpc\\Identity\\TokenIdentityFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Identity-TokenIdentityFactory.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest",
            "name": "JsonRpcRequest",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003AgetService\u0028\u0029",
            "name": "getService",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#method_getService"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003AgetAction\u0028\u0029",
            "name": "getAction",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#method_getAction"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003AgetArguments\u0028\u0029",
            "name": "getArguments",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#method_getArguments"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003AgetIdentityToken\u0028\u0029",
            "name": "getIdentityToken",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#method_getIdentityToken"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003AgetRequestId\u0028\u0029",
            "name": "getRequestId",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#method_getRequestId"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#property_action"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#property_service"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003A\u0024arguments",
            "name": "arguments",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#property_arguments"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003A\u0024requestId",
            "name": "requestId",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#property_requestId"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequest\u003A\u003A\u0024authenticationToken",
            "name": "authenticationToken",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequest.html#property_authenticationToken"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequestFactory",
            "name": "JsonRpcRequestFactory",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequestFactory.html"
        },                {
            "fqsen": "\\myrpc\\Request\\JsonRpcRequestFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Request-JsonRpcRequestFactory.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestFactoryInterface",
            "name": "RequestFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Request-RequestFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestFactoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/myrpc-Request-RequestFactoryInterface.html#method_create"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestInterface",
            "name": "RequestInterface",
            "summary": "",
            "url": "classes/myrpc-Request-RequestInterface.html"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestInterface\u003A\u003AgetService\u0028\u0029",
            "name": "getService",
            "summary": "",
            "url": "classes/myrpc-Request-RequestInterface.html#method_getService"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestInterface\u003A\u003AgetAction\u0028\u0029",
            "name": "getAction",
            "summary": "",
            "url": "classes/myrpc-Request-RequestInterface.html#method_getAction"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestInterface\u003A\u003AgetArguments\u0028\u0029",
            "name": "getArguments",
            "summary": "",
            "url": "classes/myrpc-Request-RequestInterface.html#method_getArguments"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestInterface\u003A\u003AgetIdentityToken\u0028\u0029",
            "name": "getIdentityToken",
            "summary": "",
            "url": "classes/myrpc-Request-RequestInterface.html#method_getIdentityToken"
        },                {
            "fqsen": "\\myrpc\\Request\\RequestInterface\u003A\u003AgetRequestId\u0028\u0029",
            "name": "getRequestId",
            "summary": "",
            "url": "classes/myrpc-Request-RequestInterface.html#method_getRequestId"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest",
            "name": "SimpleRequest",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003AgetService\u0028\u0029",
            "name": "getService",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#method_getService"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003AgetAction\u0028\u0029",
            "name": "getAction",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#method_getAction"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003AgetArguments\u0028\u0029",
            "name": "getArguments",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#method_getArguments"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003AgetIdentityToken\u0028\u0029",
            "name": "getIdentityToken",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#method_getIdentityToken"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003AgetRequestId\u0028\u0029",
            "name": "getRequestId",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#method_getRequestId"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003A\u0024service",
            "name": "service",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#property_service"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#property_action"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003A\u0024arguments",
            "name": "arguments",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#property_arguments"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003A\u0024requestId",
            "name": "requestId",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#property_requestId"
        },                {
            "fqsen": "\\myrpc\\Request\\SimpleRequest\u003A\u003A\u0024authenticationToken",
            "name": "authenticationToken",
            "summary": "",
            "url": "classes/myrpc-Request-SimpleRequest.html#property_authenticationToken"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse",
            "name": "JsonRpcResponse",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003AisSuccess\u0028\u0029",
            "name": "isSuccess",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#method_isSuccess"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#method_getResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#method_getError"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003AgetRequestId\u0028\u0029",
            "name": "getRequestId",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#method_getRequestId"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#property_response"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003A\u0024requestId",
            "name": "requestId",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#property_requestId"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponse\u003A\u003A\u0024errorId",
            "name": "errorId",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponse.html#property_errorId"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponseFactory",
            "name": "JsonRpcResponseFactory",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponseFactory.html"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponseFactory\u003A\u003AcreateSuccessResponse\u0028\u0029",
            "name": "createSuccessResponse",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponseFactory.html#method_createSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponseFactory\u003A\u003AcreateErrorResponse\u0028\u0029",
            "name": "createErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponseFactory.html#method_createErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\JsonRpcResponseFactory\u003A\u003AcreateExceptionResponse\u0028\u0029",
            "name": "createExceptionResponse",
            "summary": "",
            "url": "classes/myrpc-Response-JsonRpcResponseFactory.html#method_createExceptionResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseFactoryInterface",
            "name": "ResponseFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseFactoryInterface\u003A\u003AcreateSuccessResponse\u0028\u0029",
            "name": "createSuccessResponse",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseFactoryInterface.html#method_createSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseFactoryInterface\u003A\u003AcreateErrorResponse\u0028\u0029",
            "name": "createErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseFactoryInterface.html#method_createErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseFactoryInterface\u003A\u003AcreateExceptionResponse\u0028\u0029",
            "name": "createExceptionResponse",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseFactoryInterface.html#method_createExceptionResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseInterface",
            "name": "ResponseInterface",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseInterface.html"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseInterface\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseInterface.html#method_getResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseInterface\u003A\u003AisSuccess\u0028\u0029",
            "name": "isSuccess",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseInterface.html#method_isSuccess"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseInterface\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseInterface.html#method_getError"
        },                {
            "fqsen": "\\myrpc\\Response\\ResponseInterface\u003A\u003AgetRequestId\u0028\u0029",
            "name": "getRequestId",
            "summary": "",
            "url": "classes/myrpc-Response-ResponseInterface.html#method_getRequestId"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse",
            "name": "SimpleResponse",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003AisSuccess\u0028\u0029",
            "name": "isSuccess",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#method_isSuccess"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#method_getResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003AgetError\u0028\u0029",
            "name": "getError",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#method_getError"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003AgetRequestId\u0028\u0029",
            "name": "getRequestId",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#method_getRequestId"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#property_response"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003A\u0024requestId",
            "name": "requestId",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#property_requestId"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponse\u003A\u003A\u0024errorId",
            "name": "errorId",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponse.html#property_errorId"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponseFactory",
            "name": "SimpleResponseFactory",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponseFactory.html"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponseFactory\u003A\u003AcreateSuccessResponse\u0028\u0029",
            "name": "createSuccessResponse",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponseFactory.html#method_createSuccessResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponseFactory\u003A\u003AcreateErrorResponse\u0028\u0029",
            "name": "createErrorResponse",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponseFactory.html#method_createErrorResponse"
        },                {
            "fqsen": "\\myrpc\\Response\\SimpleResponseFactory\u003A\u003AcreateExceptionResponse\u0028\u0029",
            "name": "createExceptionResponse",
            "summary": "",
            "url": "classes/myrpc-Response-SimpleResponseFactory.html#method_createExceptionResponse"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchema",
            "name": "JsonSchema",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchema.html"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchema\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchema.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchema\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchema.html#method___toString"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchema\u003A\u003A\u0024jsonSchema",
            "name": "jsonSchema",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchema.html#property_jsonSchema"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchemaFactory",
            "name": "JsonSchemaFactory",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchemaFactory.html"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchemaFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchemaFactory.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchemaFactory\u003A\u003AnewSchemaFromObject\u0028\u0029",
            "name": "newSchemaFromObject",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchemaFactory.html#method_newSchemaFromObject"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchemaFactory\u003A\u003AsortSchema\u0028\u0029",
            "name": "sortSchema",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchemaFactory.html#method_sortSchema"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchemaFactory\u003A\u003AsortDefinitions\u0028\u0029",
            "name": "sortDefinitions",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchemaFactory.html#method_sortDefinitions"
        },                {
            "fqsen": "\\myrpc\\Schema\\JsonSchemaFactory\u003A\u003A\u0024datatypeFactory",
            "name": "datatypeFactory",
            "summary": "",
            "url": "classes/myrpc-Schema-JsonSchemaFactory.html#property_datatypeFactory"
        },                {
            "fqsen": "\\myrpc\\Schema\\SchemaFactoryInterface",
            "name": "SchemaFactoryInterface",
            "summary": "",
            "url": "classes/myrpc-Schema-SchemaFactoryInterface.html"
        },                {
            "fqsen": "\\myrpc\\Schema\\SchemaFactoryInterface\u003A\u003AnewSchemaFromObject\u0028\u0029",
            "name": "newSchemaFromObject",
            "summary": "",
            "url": "classes/myrpc-Schema-SchemaFactoryInterface.html#method_newSchemaFromObject"
        },                {
            "fqsen": "\\myrpc\\Schema\\SchemaInterface",
            "name": "SchemaInterface",
            "summary": "",
            "url": "classes/myrpc-Schema-SchemaInterface.html"
        },                {
            "fqsen": "\\myrpc\\SchemaServer",
            "name": "SchemaServer",
            "summary": "",
            "url": "classes/myrpc-SchemaServer.html"
        },                {
            "fqsen": "\\myrpc\\SchemaServer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-SchemaServer.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\SchemaServer\u003A\u003AgetServiceSchema\u0028\u0029",
            "name": "getServiceSchema",
            "summary": "",
            "url": "classes/myrpc-SchemaServer.html#method_getServiceSchema"
        },                {
            "fqsen": "\\myrpc\\SchemaServer\u003A\u003A\u0024handlerFactory",
            "name": "handlerFactory",
            "summary": "",
            "url": "classes/myrpc-SchemaServer.html#property_handlerFactory"
        },                {
            "fqsen": "\\myrpc\\SchemaServer\u003A\u003A\u0024schemaFactory",
            "name": "schemaFactory",
            "summary": "",
            "url": "classes/myrpc-SchemaServer.html#property_schemaFactory"
        },                {
            "fqsen": "\\myrpc\\Serializer\\JsonSerializer",
            "name": "JsonSerializer",
            "summary": "JsonSerializer\u0020deals\u0020with\u0020object\u0020\u0028un\u0029wrapping,\u0020marshalling,\u0020protocol\u0020representation\u0020\u003C\u003E\u0020business\u0020layer",
            "url": "classes/myrpc-Serializer-JsonSerializer.html"
        },                {
            "fqsen": "\\myrpc\\Serializer\\JsonSerializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Serializer-JsonSerializer.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Serializer\\JsonSerializer\u003A\u003Adenormalize\u0028\u0029",
            "name": "denormalize",
            "summary": "Safely\u0020un\u002Dserialize\u0020any\u0020class\nNO\u0020support\u0020for\u0020interfaces\nNo\u0020support\u0020for\u0020abstract\u0020classes",
            "url": "classes/myrpc-Serializer-JsonSerializer.html#method_denormalize"
        },                {
            "fqsen": "\\myrpc\\Serializer\\JsonSerializer\u003A\u003AFORMAT",
            "name": "FORMAT",
            "summary": "",
            "url": "classes/myrpc-Serializer-JsonSerializer.html#constant_FORMAT"
        },                {
            "fqsen": "\\myrpc\\Serializer\\JsonSerializer\u003A\u003ARECURSION_DEPTH",
            "name": "RECURSION_DEPTH",
            "summary": "",
            "url": "classes/myrpc-Serializer-JsonSerializer.html#constant_RECURSION_DEPTH"
        },                {
            "fqsen": "\\myrpc\\Serializer\\JsonSerializer\u003A\u003A\u0024serializer",
            "name": "serializer",
            "summary": "",
            "url": "classes/myrpc-Serializer-JsonSerializer.html#property_serializer"
        },                {
            "fqsen": "\\myrpc\\Serializer\\SerializerInterface",
            "name": "SerializerInterface",
            "summary": "",
            "url": "classes/myrpc-Serializer-SerializerInterface.html"
        },                {
            "fqsen": "\\myrpc\\Serializer\\SerializerInterface\u003A\u003Adenormalize\u0028\u0029",
            "name": "denormalize",
            "summary": "",
            "url": "classes/myrpc-Serializer-SerializerInterface.html#method_denormalize"
        },                {
            "fqsen": "\\myrpc\\Validator\\IsValidatableInterface",
            "name": "IsValidatableInterface",
            "summary": "",
            "url": "classes/myrpc-Validator-IsValidatableInterface.html"
        },                {
            "fqsen": "\\myrpc\\Validator\\IsValidatableInterface\u003A\u003AvalidatableObject\u0028\u0029",
            "name": "validatableObject",
            "summary": "",
            "url": "classes/myrpc-Validator-IsValidatableInterface.html#method_validatableObject"
        },                {
            "fqsen": "\\myrpc\\Validator\\Symfony",
            "name": "Symfony",
            "summary": "Symfony\u0020validator\u0020handles\u0020user\u0020types\u0020validation\u0020on\u0020input\n\u002D\u0020supports\u0020attributes\u0020constraints\n\u002D\u0020supports\u0020classMetadata",
            "url": "classes/myrpc-Validator-Symfony.html"
        },                {
            "fqsen": "\\myrpc\\Validator\\Symfony\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Validator-Symfony.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Validator\\Symfony\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "",
            "url": "classes/myrpc-Validator-Symfony.html#method_validate"
        },                {
            "fqsen": "\\myrpc\\Validator\\Symfony\u003A\u003A\u0024validator",
            "name": "validator",
            "summary": "",
            "url": "classes/myrpc-Validator-Symfony.html#property_validator"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult",
            "name": "SymfonyResult",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#method___construct"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#method_getName"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003AgetCode\u0028\u0029",
            "name": "getCode",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#method_getCode"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#method_getMessage"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#property_name"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003A\u0024code",
            "name": "code",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#property_code"
        },                {
            "fqsen": "\\myrpc\\Validator\\SymfonyResult\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/myrpc-Validator-SymfonyResult.html#property_message"
        },                {
            "fqsen": "\\myrpc\\Validator\\ValidatorInterface",
            "name": "ValidatorInterface",
            "summary": "",
            "url": "classes/myrpc-Validator-ValidatorInterface.html"
        },                {
            "fqsen": "\\myrpc\\Validator\\ValidatorInterface\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "",
            "url": "classes/myrpc-Validator-ValidatorInterface.html#method_validate"
        },                {
            "fqsen": "\\myrpc\\Validator\\ValidatorResultInterface",
            "name": "ValidatorResultInterface",
            "summary": "",
            "url": "classes/myrpc-Validator-ValidatorResultInterface.html"
        },                {
            "fqsen": "\\myrpc\\Validator\\ValidatorResultInterface\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/myrpc-Validator-ValidatorResultInterface.html#method_getName"
        },                {
            "fqsen": "\\myrpc\\Validator\\ValidatorResultInterface\u003A\u003AgetCode\u0028\u0029",
            "name": "getCode",
            "summary": "",
            "url": "classes/myrpc-Validator-ValidatorResultInterface.html#method_getCode"
        },                {
            "fqsen": "\\myrpc\\Validator\\ValidatorResultInterface\u003A\u003AgetMessage\u0028\u0029",
            "name": "getMessage",
            "summary": "",
            "url": "classes/myrpc-Validator-ValidatorResultInterface.html#method_getMessage"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\myrpc",
            "name": "myrpc",
            "summary": "",
            "url": "namespaces/myrpc.html"
        },                {
            "fqsen": "\\myrpc\\Datatype",
            "name": "Datatype",
            "summary": "",
            "url": "namespaces/myrpc-datatype.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal",
            "name": "Internal",
            "summary": "",
            "url": "namespaces/myrpc-datatype-internal.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1\\Response",
            "name": "Response",
            "summary": "",
            "url": "namespaces/myrpc-datatype-internal-v1-response.html"
        },                {
            "fqsen": "\\myrpc\\Datatype\\Internal\\v1",
            "name": "v1",
            "summary": "",
            "url": "namespaces/myrpc-datatype-internal-v1.html"
        },                {
            "fqsen": "\\myrpc\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/myrpc-exception.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Context",
            "name": "Context",
            "summary": "",
            "url": "namespaces/myrpc-handler-context.html"
        },                {
            "fqsen": "\\myrpc\\Handler",
            "name": "Handler",
            "summary": "",
            "url": "namespaces/myrpc-handler.html"
        },                {
            "fqsen": "\\myrpc\\Handler\\Worker",
            "name": "Worker",
            "summary": "",
            "url": "namespaces/myrpc-handler-worker.html"
        },                {
            "fqsen": "\\myrpc\\Identity",
            "name": "Identity",
            "summary": "",
            "url": "namespaces/myrpc-identity.html"
        },                {
            "fqsen": "\\myrpc\\Request",
            "name": "Request",
            "summary": "",
            "url": "namespaces/myrpc-request.html"
        },                {
            "fqsen": "\\myrpc\\Response",
            "name": "Response",
            "summary": "",
            "url": "namespaces/myrpc-response.html"
        },                {
            "fqsen": "\\myrpc\\Schema",
            "name": "Schema",
            "summary": "",
            "url": "namespaces/myrpc-schema.html"
        },                {
            "fqsen": "\\myrpc\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "namespaces/myrpc-serializer.html"
        },                {
            "fqsen": "\\myrpc\\Validator",
            "name": "Validator",
            "summary": "",
            "url": "namespaces/myrpc-validator.html"
        }            ]
);
